---
title: "Descriptive Analysis of a Multilevel Data Set"
author: "Katherine Wolf"
date: "February 20, 2020"
output:
    pdf_document:
    latex_engine: xelatex
mainfont: Calibri
monofont: Lucida Console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

```


```{r my code}

# need to call the libraries every time you begin a new R session
library(dplyr)
library(ggplot2)
library(nnet)
library(tidyverse)
library(tableone)
library(xtable)
library(knitr)
library(tableone)
library(kableExtra)

# read in data – suppose the file dataset.csv contains continuous variables var1 and var2, and a binary variable outcome
nyses_raw_data <- read_csv("NYSES data for class.csv")

# make working data file
nyses_to_edit <- nyses_raw_data

# id
nyses_to_edit$id <- nyses_to_edit$QKEY2

# community district
nyses_to_edit$`Community district` <- nyses_to_edit$cd

# neighborhood median income
nyses_to_edit$`Neighborhood median income ($)` <- nyses_to_edit$medinc

# neighborhood percent below poverty
nyses_to_edit$`Neighborhood poverty (%)` <- nyses_to_edit$pbelowpv

# borough
borough_labels <- 
  c("Bronx",
    "Brooklyn", 
    "Manhattan", 
    "Queens", 
    "Staten Island") # (value = order)

nyses_to_edit$Borough <- 
  factor(nyses_to_edit$boro, 
         labels = borough_labels)

# age
age_labels <- 
  c("18-24",
    "25-34", 
    "35-44", 
    "45-54", 
    "55-64", 
    "65+") # (value = order)

nyses_to_edit$`Age (years)` <- 
  factor(nyses_to_edit$agecat, 
         labels = age_labels)

# race/ethnicity
race_labels <- 
  c("White",
    "African American", 
    "Asian", 
    "Hispanic/Latinx", 
    "Other") # (value = order)

nyses_to_edit$`Race/ethnicity` <- 
  factor(nyses_to_edit$racecat, labels = race_labels)

# education
ed_labels <- 
  c("Less than high school",
    "High school/GED", 
    "Some college", 
    "College graduate", 
    "Graduate work") # (value = order)

nyses_to_edit$`Education` <- 
  factor(nyses_to_edit$edcat, labels = ed_labels)

# income
income_labels <- 
  c(">= 40,000",
    "40,001 to 80,000", 
    "> 80,000") # (value = order)

nyses_to_edit$`Income ($)` <- 
  factor(nyses_to_edit$inc3cat, labels = income_labels)

# binge drinking
binge_labels <- 
  c("No", 
    "Yes") # (value = order)

nyses_to_edit$`Binge drinking` <- 
  factor(nyses_to_edit$binge, 
         labels = binge_labels)

nyses_analyze <- 
  nyses_to_edit %>% 
  select(id, 
         `Community district`,
         `Neighborhood median income ($)`, 
         `Neighborhood poverty (%)`, 
         Borough, 
         `Age (years)`, 
         `Race/ethnicity`, 
         Education, 
         `Income ($)`, 
         `Binge drinking`)

```


```{r make a table one}

# create a list of variables for the table 
# (not including the stratification variable)
table_one_variables <- c("Neighborhood median income ($)",
                         "Neighborhood poverty (%)",
                         "Borough", 
                         "Age (years)", 
                         "Race/ethnicity", 
                         "Education", 
                         "Income ($)")

# create a list of which ones are categorical (factor)
factor_variables <- c("Borough",
                      "Age (years)", 
                      "Race/ethnicity", 
                      "Education", 
                      "Income ($)")

table_1 <- CreateTableOne(vars = table_one_variables, 
                          factorVars = factor_variables,
                          strata = "Binge drinking",
                          data = nyses_analyze,
                          test = FALSE, 
                          includeNA = TRUE)

save(table_1, 
     file = "table_1.rdata")

# print(table.1) # Standard output

# Creates a formatted table, using kable from the knitr package
# Would want to clean this up for publication purposes:
hi <- kable(print(table_1,
                  showAllLevels = TRUE,
                  printToggle = FALSE,
                  noSpaces = TRUE,
                  catDigits = 1,
                  contDigits = 1),
            col.names = c("Level", "No binge drinking", "Binge drinking"),
            caption=paste("Descriptive statistics for participants in",
                          "NYSES cohort, stratified by binge drinking."))


# hi <- kable(print(table_1,
#                    showAllLevels = TRUE,
#                    printToggle = FALSE,
#                    noSpaces = TRUE,
#                    catDigits=1,
#                    contDigits=1),
#       caption=paste("Descriptive statistics for participants in",
#                     "NYSES cohort, stratified by binge drinking."))

hi

```

# Univariate analyses

```{r}

nyses_analyze %>%  
  summary()

ggplot(data)

```

# Bivariate analyses by outcome

## Neighborhood median income

```{r}

# neighborhood median income
nyses_analyze %>% 
  group_by(`Binge drinking`) %>% 
  summarise(Mean = mean(`Neighborhood median income ($)`), 
            Median = median(`Neighborhood median income ($)`), 
            `Standard deviation` = sd(`Neighborhood median income ($)`), 
            Minimum = range(`Neighborhood median income ($)`)[1], 
            Maximum = range(`Neighborhood median income ($)`)[2])

# neighborhood median income
ggplot(data = nyses_to_edit, 
       aes(x = `Binge drinking`, 
           y = `Neighborhood median income ($)`)) +
  geom_boxplot()




```

## Neighborhood percent in poverty

```{r univariate continuous analyses}

# neighborhood percent in poverty
nyses_analyze %>% 
  group_by(`Binge drinking`) %>% 
  summarise(Mean = mean(`Neighborhood poverty (%)`), 
            Median = median(`Neighborhood poverty (%)`), 
            `Standard deviation` = sd(`Neighborhood poverty (%)`), 
            Minimum = range(`Neighborhood poverty (%)`)[1], 
            Maximum = range(`Neighborhood poverty (%)`)[2])

# neighborhood median income
ggplot(data = nyses_to_edit, 
       aes(x = `Binge drinking`, 
           y = `Neighborhood median income ($)`)) +
  geom_boxplot()


# neighborhood percent in poverty



`Neighborhood median income ($)`


# check for missing data (nas)
na_counts <- 
  map(nyses_to_edit,  # cycles through all variables
      function(x) sum(is.na(x)))  # sums all "T" values from nas
na_counts

range(nyses_to_edit$pbelowpv)
ggplot(data = nyses_to_edit, aes(x = binge, y = pbelowpv)) +
  geom_boxplot()

range(nyses_to_edit$cd)
ggplot(data = nyses_to_edit, aes(x = binge, y = cd)) +
  geom_boxplot()



range(nyses_to_edit$medinc)
ggplot(data = nyses_to_edit, aes(x = binge, y = medinc)) +
  geom_boxplot()

```



```{r correlation table}

```



```{r code from assignment, eval=FALSE, include=FALSE}

# # load packages used in this assignment
# # only need to install packages once
# install.packages("dplyr") 
# install.packages("ggplot2")
# install.packages("nnet")

# need to call the libraries every time you begin a new R session
library(dplyr)
library(ggplot2)
library(nnet)

# read in data – suppose the file dataset.csv contains continuous variables var1 and var2, and a binary variable outcome
df <- read.csv("c:/dataset.csv")

# create a categorical variable from a continuous variable 
df$catvar1 <- df$var1
df$catvar1 <- ifelse(df$catvar1<=500,0,ifelse(df$catvar1>500,1,NA))

# describe variables
summary(df$var1)
table(df$var1)
hist(df$var1)

with(df, table(var1,var2))
with(df, table(var1,var2, exclude=NULL))

df %>%
  group_by(catvar1) %>% summarise(mean_outcome = mean(outcome))


# bivariable relations

# to do a Pearson's chi-squared test 
x2 <- chisq.test(df$var1, df$var2)

# to see the results of the test
x2 

# to see the table of observed
x2$observed

# to see the percents by row 
prop.table(x2$observed, 1) 

# to see the percents by column
prop.table(x2$observed, 2)

# calculate correlation between variables 
cor.test(df$var1, df$var2)

# summarize relationship between variables in a plot with a lowess line 
ggplot(df) + geom_point(aes(x=var1, y=outcome))  + 
  geom_line(aes(x=var1, y=predict(loess(outcome~var1)))) + theme_bw()


```


# Report

## 
n = 4000 participants, for whom 40 were missing age, 112 were missing race, 77 were misisng education, and 580 were missing data on income.



```{r ref.label=knitr::all_labels(), echo = T, eval = F}

```

